### ISSUE TITLE
(SP: 3) Implement loading and validation of the file on Add photo step

### ISSUE THREAD

**Issue by vlad-khrychov** [Space2Study-UA-1156/Client-02#165]
UserStory: #65 , #64
Blocked by: #163 , #164 

## Description
Implement loading and validation of the file on Add photo step

## Design 

![Image](https://github.com/ita-social-projects/Space2Study-Client-mvp/assets/90138904/359b6911-668a-47c8-9f39-549bc578491d)

## Acceptance Criteria
- [x] When file is loaded it should send file to server
- [x] When file is not `.png`, `.jpg` or `.jpeg` it should validate and throw an error

**Comment by Olenka-Hryk** [comment]
- [x] When file is not `.png`, `.jpg` or `.jpeg` it should validate and throw an error -> It was resolved in Issue #163 and implemented in PR #177
